# Generated by Django 4.2.6 on 2024-05-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vendor Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('vendor_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Vendor Code')),
                ('on_time_delivery_rate', models.FloatField(verbose_name='On-Time Delivery Rate')),
                ('quality_rating_avg', models.FloatField(verbose_name='Quality Rating Average')),
                ('average_response_time', models.FloatField(verbose_name='Average Response Time')),
                ('fulfillment_rate', models.FloatField(verbose_name='Fulfillment Rate')),
            ],
        ),
    ]
