# Generated by Django 4.2.6 on 2024-05-03 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_vendor_delivery_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.FloatField(null=True, verbose_name='Average Response Time'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.FloatField(null=True, verbose_name='Fulfillment Rate'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='on_time_delivery_rate',
            field=models.FloatField(null=True, verbose_name='On-Time Delivery Rate'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quality_rating_avg',
            field=models.FloatField(null=True, verbose_name='Quality Rating Average'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True, verbose_name='PO Number')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date')),
                ('items', models.JSONField(verbose_name='Items')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('quality_rating', models.FloatField(null=True, verbose_name='Quality Rating')),
                ('issue_date', models.DateTimeField(verbose_name='Issue Date')),
                ('acknowledgment_date', models.DateTimeField(null=True, verbose_name='Acknowledgment Date')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.vendor', verbose_name='Vendor')),
            ],
        ),
    ]
