# Generated by Django 4.2.6 on 2024-05-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_alter_vendor_average_response_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(blank=True, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='PO Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quality_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Quality Rating'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Status'),
        ),
    ]
