# Generated by Django 4.2.6 on 2024-05-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0004_alter_purchaseorder_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='delivery_days',
            field=models.IntegerField(max_length=20, null=True, verbose_name='Total Day Deliver'),
        ),
    ]
