# Generated by Django 4.2.6 on 2024-05-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0006_purchaseorder__delivery_date_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Average Response Time'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Fulfillment Rate'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='on_time_delivery_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='On-Time Delivery Rate'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quality_rating_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Quality Rating Average'),
        ),
    ]
