# Generated by Django 4.1.10 on 2024-05-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0009_alter_vendor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
