# Generated by Django 4.1.10 on 2024-05-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0010_alter_vendor_address_alter_vendor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=100, verbose_name='Status'),
        ),
    ]
