# Generated by Django 4.1.10 on 2024-05-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0012_alter_purchaseorder_acknowledgment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Issue Date'),
        ),
    ]
