# Generated by Django 4.1.10 on 2024-05-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0015_historicalperformance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalperformance',
            options={},
        ),
    ]
