# Generated by Django 4.1.10 on 2024-05-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0017_alter_historicalperformance_average_response_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalperformance',
            options={'verbose_name': 'Historical Performance', 'verbose_name_plural': 'Historical Performances'},
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='average_response_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='fulfillment_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='quality_rating_avg',
            field=models.FloatField(default=0),
        ),
    ]
